name: bloc_to_do
description: '''
  ToDoList is a convenient task management tool developed using Flutter. 
  With ToDoList, you can easily add, view, and delete tasks, as well as track their completion status. 
  Its simple and intuitive interface helps you organize your workflow effectively and increase productivity. 
  Start using ToDoList now and streamline your life effortlessly!
'''
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
